alias ll='ls -l'
alias vim='mvim -v'
alias dev='ssh -X fanguiju@200.21.18.2'
alias rm='rmtrash'
alias grep='grep --color'
alias test_env='cd /Users/mickeyfan/Projects/demo/test; source test_env/bin/activate'
alias ipython='cd /Users/mickeyfan/Projects/demo/test; source test_env/bin/activate; ipython'
